### ISSUE TITLE
initialise the repo

### ISSUE THREAD

**Issue by mrennekamp** [sagemath/combinat#1]
add a readme? 
[readme.txt](https://github.com/sagemath/combinat/files/869104/readme.txt)

**Comment by haraldschilly** [comment]
well, send a pull request to earn your :1st_place_medal: for being a contributor :exclamation: 

besides that there should also be a license. I suggest the liberal creative commons CC-BY 4.0.

**Comment by mrennekamp** [comment]
I need to be able to fork it to do a pull request, right? And I can't do much on command line by cloning it and then trying to commit.

**Comment by mrennekamp** [comment]
Actually, if Thierry means this repo to move to in "I'll move the 'misc' and 'patches' repos to github and link them from the wiki.", then he would be fine if he has permissions to add some files...

**Comment by haraldschilly** [comment]
good, I thought forking is already possible since one can have empty repos

**Comment by mrennekamp** [comment]
Thank you and sorry for the confusion!

On Mar 25, 2017 7:44 AM, Harald Schilly <notifications@github.com> wrote:

good, I thought forking is already possible since one can have empty repos
