### ISSUE TITLE
setup domain name

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/combinat#2]
hello @mrennekamp 

I don't know the exact plans, but I can quickly setup an empty page to get started for a domain hosted here.

**Comment by mrennekamp** [comment]
@haraldschilly 
I think @nthiery wants us to redirect most pages to SageWiki. Default should probably be leave as is so that each page supports a manual redirect. The index.html that I made does that, so all we need are some uploaded files (which may be up Monday?).

**Comment by nthiery** [comment]
+1; in fact redirecting *all* pages would be just fine. Thanks!
